Repository bernardoveras/studle, pull requests merged in 2024-03, with the labels that each got.

#4 Documentation Update
  .github/ISSUE_TEMPLATE/-core-team-only--new-approved-feature.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#6 feat: add user session
  lib/src/core/dependecy_injection/injector.dart
  lib/src/core/dependecy_injection/injector_extension.dart
  lib/src/core/router.dart
  lib/src/core/user_session.dart
  lib/src/modules/authentication/ui/store/login_store.dart
Labels: enhancement

#9 feat: add campaign page
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/src/core/extensions/query_parameters_extension.dart
  lib/src/core/router.dart
  lib/src/core/ui/design_system/themes/theme.dart
  lib/src/core/ui/design_system/widgets/buttons/solid_button_widget.dart
  lib/src/core/utils/redirect_to_url.dart
  lib/src/modules/campaigns/ui/pages/campaign_page.dart
  lib/src/modules/campaigns/ui/parameters/campaign_page_parameter.dart
  lib/src/modules/campaigns/ui/widgets/campaign_header.dart
  pubspec.lock
  pubspec.yaml
  test/src/modules/campaigns/ui/parameters/campaign_page_parameter_test.dart
Labels: enhancement

#12 style: add typographies and change pages
  lib/src/core/ui/design_system/design_system.dart
  lib/src/core/ui/design_system/typographies/button/button.dart
  lib/src/core/ui/design_system/typographies/button/button_1_typography.dart
  lib/src/core/ui/design_system/typographies/button/button_2_typography.dart
  lib/src/core/ui/design_system/typographies/button/button_3_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading.dart
  lib/src/core/ui/design_system/typographies/heading/heading_1_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading_2_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading_3_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading_4_typography.dart
  lib/src/core/ui/design_system/typographies/text/text.dart
  lib/src/core/ui/design_system/typographies/text/text_1_typography.dart
  lib/src/core/ui/design_system/typographies/text/text_2_typography.dart
  lib/src/core/ui/design_system/typographies/text/text_3_typography.dart
  lib/src/core/ui/design_system/typographies/typographies.dart
  lib/src/core/ui/design_system/widgets/buttons/solid_button_widget.dart
  lib/src/core/ui/design_system/widgets/default_text_field.dart
  lib/src/modules/authentication/ui/pages/login_page.dart
  lib/src/modules/campaigns/ui/pages/campaign_page.dart
Labels: enhancement

#15 Onboarding
  assets/images/onboarding1.png
  assets/images/onboarding2.png
  assets/images/onboarding3.png
  lib/src/core/image_source_constants.dart
  lib/src/core/router.dart
  lib/src/modules/authentication/ui/pages/login_page.dart
  lib/src/modules/onboarding/domain/entities/onboarding_entity.dart
  lib/src/modules/onboarding/ui/pages/onboarding_page.dart
  lib/src/modules/onboarding/ui/stores/onboarding_store.dart
  lib/src/modules/onboarding/ui/widgets/onboarding_bottom_sheet.dart
  lib/src/modules/onboarding/ui/widgets/onboarding_step.dart
  pubspec.yaml
Labels: enhancement

#16 Local Storage Service
  README.md
  assets/images/onboarding1.png
  assets/images/onboarding2.png
  assets/images/onboarding3.png
  lib/src/core/constants/image_source_constants.dart
  lib/src/core/constants/local_storage_key.dart
  lib/src/core/constants/text_constants.dart
  lib/src/core/exceptions/exceptions.dart
  lib/src/core/exceptions/not_found_exception.dart
  lib/src/core/exceptions/unknow_exception.dart
  lib/src/core/router.dart
  lib/src/core/services/local_storage/data/services/local_storage_shared_preferences_service_impl.dart
  lib/src/core/services/local_storage/domain/services/i_local_storage_service.dart
  lib/src/core/ui/design_system/colors/base_color.dart
  lib/src/core/ui/design_system/colors/monochromatic_colors.dart
  lib/src/core/ui/design_system/design_system.dart
  lib/src/core/ui/design_system/themes/theme.dart
  lib/src/core/ui/design_system/typographies/button/button.dart
  lib/src/core/ui/design_system/typographies/button/button_1_typography.dart
  lib/src/core/ui/design_system/typographies/button/button_2_typography.dart
  lib/src/core/ui/design_system/typographies/button/button_3_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading.dart
  lib/src/core/ui/design_system/typographies/heading/heading_1_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading_2_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading_3_typography.dart
  lib/src/core/ui/design_system/typographies/heading/heading_4_typography.dart
  lib/src/core/ui/design_system/typographies/text/text.dart
  lib/src/core/ui/design_system/typographies/text/text_1_typography.dart
  lib/src/core/ui/design_system/typographies/text/text_2_typography.dart
  lib/src/core/ui/design_system/typographies/text/text_3_typography.dart
  lib/src/core/ui/design_system/typographies/typographies.dart
  lib/src/core/ui/design_system/widgets/buttons/solid_button_widget.dart
  lib/src/core/ui/design_system/widgets/default_text_field.dart
  lib/src/modules/authentication/ui/pages/login_page.dart
  lib/src/modules/authentication/ui/store/login_store.dart
  lib/src/modules/campaigns/ui/pages/campaign_page.dart
  lib/src/modules/campaigns/ui/widgets/campaign_header.dart
  lib/src/modules/onboarding/domain/entities/onboarding_entity.dart
  lib/src/modules/onboarding/ui/pages/onboarding_page.dart
  lib/src/modules/onboarding/ui/stores/onboarding_store.dart
  lib/src/modules/onboarding/ui/widgets/onboarding_bottom_sheet.dart
  lib/src/modules/onboarding/ui/widgets/onboarding_step.dart
  pubspec.yaml
  test/src/core/services/local_storage/data/services/local_storage_shared_preferences_service_impl_test.dart
Labels: enhancement

#17 Local Storage Service
  lib/src/core/constants/image_source_constants.dart
  lib/src/core/constants/local_storage_key.dart
  lib/src/core/constants/text_constants.dart
  lib/src/core/exceptions/exceptions.dart
  lib/src/core/exceptions/not_found_exception.dart
  lib/src/core/exceptions/unknow_exception.dart
  lib/src/core/services/local_storage/data/services/local_storage_shared_preferences_service_impl.dart
  lib/src/core/services/local_storage/domain/services/i_local_storage_service.dart
  lib/src/core/ui/design_system/widgets/default_text_field.dart
  lib/src/modules/authentication/ui/pages/login_page.dart
  lib/src/modules/authentication/ui/store/login_store.dart
  lib/src/modules/onboarding/ui/stores/onboarding_store.dart
  pubspec.yaml
  test/src/core/services/local_storage/data/services/local_storage_shared_preferences_service_impl_test.dart
Labels: enhancement

#23 Notifications (partial)
  assets/images/notifications_illustration.png
  ios/Podfile.lock
  lib/src/core/constants/image_source_constants.dart
  lib/src/core/constants/local_storage_key.dart
  lib/src/core/dependecy_injection/injector.dart
  lib/src/core/dependecy_injection/injector_extension.dart
  lib/src/core/router.dart
  lib/src/core/ui/design_system/colors/monochromatic_colors.dart
  lib/src/core/ui/design_system/themes/theme.dart
  lib/src/core/ui/design_system/widgets/buttons/solid_button.dart
  lib/src/core/ui/design_system/widgets/skeletons/skeleton_container.dart
  lib/src/core/ui/widgets/default_app_bar.dart
  lib/src/core/ui/widgets/states/empty_state_display.dart
  lib/src/core/ui/widgets/states/error_state_display.dart
  lib/src/core/ui/widgets/states/states.dart
  lib/src/core/utils/nullable_value.dart
  lib/src/modules/home/ui/pages/home_page.dart
  lib/src/modules/notifications/data/services/notification_local_service_impl.dart
  lib/src/modules/notifications/domain/entities/notification_entity.dart
  lib/src/modules/notifications/domain/enums/notification_link_type_enum.dart
  lib/src/modules/notifications/domain/enums/notification_status_enum.dart
  lib/src/modules/notifications/domain/services/i_notification_service.dart
  lib/src/modules/notifications/ui/cubits/notification_list_cubit.dart
  lib/src/modules/notifications/ui/cubits/notification_list_state.dart
  lib/src/modules/notifications/ui/pages/notification_list_page.dart
  lib/src/modules/notifications/ui/widgets/lists/notification_list.dart
  lib/src/modules/notifications/ui/widgets/notification_card.dart
  lib/src/modules/notifications/ui/widgets/notification_skeleton_card.dart
  lib/src/modules/notifications/ui/widgets/notification_tab_bar.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/notification_entity_mock.dart
  test/src/core/helpers/date_helper_test.dart
  test/src/modules/notifications/data/services/notification_local_service_impl_test.dart
  test/src/modules/notifications/domain/entities/notification_entity_test.dart
Labels: enhancement

#25 Profile
  lib/src/core/constants/text_constants.dart
  lib/src/core/dependecy_injection/injector_extension.dart
  lib/src/core/extensions/string_extension.dart
  lib/src/core/helpers/cnpj_helper.dart
  lib/src/core/helpers/cpf_helper.dart
  lib/src/core/helpers/zip_code_helper.dart
  lib/src/core/router.dart
  lib/src/core/ui/design_system/colors/monochromatic_colors.dart
  lib/src/core/ui/design_system/design_system.dart
  lib/src/core/ui/design_system/themes/theme.dart
  lib/src/core/ui/design_system/widgets/buttons/solid_button.dart
  lib/src/core/ui/design_system/widgets/default_text_field.dart
  lib/src/core/ui/design_system/widgets/modals/confirmation_modal.dart
  lib/src/core/ui/design_system/widgets/modals/default_modal.dart
  lib/src/core/ui/design_system/widgets/modals/default_modal_header.dart
  lib/src/core/ui/design_system/widgets/modals/modals.dart
  lib/src/core/ui/widgets/default_app_bar.dart
  lib/src/core/ui/widgets/tiles/default_list_tile.dart
  lib/src/core/utils/regex_utils.dart
  lib/src/core/validators/cep_validatorless.dart
  lib/src/core/validators/cnpj_validatorless.dart
  lib/src/core/validators/cpf_validatorless.dart
  lib/src/core/validators/date_validatorless.dart
  lib/src/core/validators/phone_number_validatorless.dart
  lib/src/modules/authentication/data/services/auth_mock_service_impl.dart
  lib/src/modules/authentication/domain/entities/user_entity.dart
  lib/src/modules/authentication/domain/enums/person_gender_enum.dart
  lib/src/modules/home/ui/pages/home_page.dart
  lib/src/modules/profile/ui/pages/personal_data_page.dart
  lib/src/modules/profile/ui/pages/profile_page.dart
  lib/src/modules/profile/ui/pages/student_identity_page.dart
  lib/src/modules/profile/ui/widgets/profile_picture.dart
  lib/src/modules/profile/ui/widgets/student_identity_card.dart
  lib/src/modules/questions/ui/pages/question_page.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/user_entity_mock.dart
  test/src/modules/authentication/domain/entities/user_entity_test.dart
Labels: enhancement

#28 New Snackbar
  README.md
  lib/src/core/ui/design_system/themes/theme.dart
  lib/src/core/ui/services/snackbar/snackbar_service.dart
  lib/src/modules/authentication/ui/pages/login_page.dart
Labels: enhancement

#24 Feat/activities
  lib/src/core/router.dart
  lib/src/core/utils/copy_text.dart
  lib/src/modules/activities/ui/pages/additional_activities_page.dart
  lib/src/modules/activities/ui/widgets/activity_progress_card_widget.dart
  lib/src/modules/activities/ui/widgets/teacher_information_card_widget.dart
  lib/src/modules/home/ui/pages/home_page.dart
Labels: enhancement

#31 Feat/snackbar
  lib/src/core/ui/design_system/themes/theme.dart
  lib/src/core/ui/services/snackbar/snackbar_service.dart
  lib/src/modules/authentication/ui/pages/login_page.dart
Labels: enhancement

#32 Photo Picker Service
  ios/Runner/Info.plist
  lib/src/core/dependecy_injection/injector.dart
  lib/src/core/dependecy_injection/injector_extension.dart
  lib/src/core/services/image_picker/data/services/image_picker_service_impl.dart
  lib/src/core/services/image_picker/domain/exceptions/not_found_exception.dart
  lib/src/core/services/image_picker/domain/services/i_image_picker_service.dart
  lib/src/core/services/image_picker/enums/image_source_photo_picker_enum.dart
  lib/src/modules/profile/ui/widgets/profile_picture.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#33 Feat/permission handler on profile picture
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Runner/Info.plist
  lib/src/core/utils/hide_keyboard.dart
  lib/src/modules/authentication/ui/pages/login_page.dart
  lib/src/modules/profile/ui/widgets/profile_picture.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#34 Refactor/notifications
  lib/src/modules/notifications/data/services/notification_local_service_impl.dart
  lib/src/modules/notifications/domain/services/i_notification_service.dart
  lib/src/modules/notifications/ui/cubits/notification_list_cubit.dart
  lib/src/modules/notifications/ui/pages/notification_list_page.dart
  lib/src/modules/notifications/ui/widgets/lists/notification_list.dart
  lib/src/modules/notifications/ui/widgets/notification_tab_bar.dart
Labels: refactor

#35 refactor: remove change password when is unlogged, add mail redirect …
  assets/images/question.png
  assets/images/support_illustration.png
  lib/src/core/constants/image_source_constants.dart
  lib/src/core/ui/design_system/widgets/default_expansion_tile.dart
  lib/src/core/utils/encode_query_parameters.dart
  lib/src/modules/questions/ui/pages/question_page.dart
Labels: refactor

#36 Refactor/change bottom sheets to persistent buttons
  lib/src/core/ui/design_system/themes/theme.dart
  lib/src/modules/activities/ui/pages/additional_activities_page.dart
  lib/src/modules/campaigns/ui/pages/campaign_page.dart
  lib/src/modules/home/ui/pages/home_page.dart
  lib/src/modules/onboarding/ui/pages/onboarding_page.dart
  lib/src/modules/profile/ui/pages/profile_page.dart
  lib/src/modules/questions/ui/pages/question_page.dart
Labels: refactor

#37 Update README.md
  README.md
Labels: documentation

#38 Change app name to studle
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/studle/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/main.dart
  lib/src/app.dart
  lib/src/core/ui/widgets/states/error_state_display.dart
  lib/src/modules/activities/ui/pages/additional_activities_page.dart
  lib/src/modules/profile/ui/widgets/student_identity_card.dart
  lib/src/modules/questions/ui/pages/question_page.dart
  pubspec.yaml
  test/mocks/calendar_activity_entity_mock.dart
  test/mocks/calendar_day_off_entity_mock.dart
  test/mocks/calendar_entity_mock.dart
  test/mocks/login_with_student_registration_mock.dart
  test/mocks/notification_entity_mock.dart
  test/mocks/user_entity_mock.dart
  test/src/core/extension_types/guid_test.dart
  test/src/core/helpers/date_helper_test.dart
  test/src/core/services/local_storage/data/services/local_storage_shared_preferences_service_impl_test.dart
  test/src/modules/authentication/data/services/auth_mock_service_impl_test.dart
  test/src/modules/authentication/domain/dtos/login_with_student_registration_dto_test.dart
  test/src/modules/authentication/domain/entities/user_entity_test.dart
  test/src/modules/calendar/domain/entities/calendar_activity_entity_test.dart
  test/src/modules/calendar/domain/entities/calendar_day_off_entity_test.dart
  test/src/modules/calendar/domain/entities/calendar_entity_test.dart
  test/src/modules/campaigns/ui/parameters/campaign_page_parameter_test.dart
  test/src/modules/notifications/domain/entities/notification_entity_test.dart
Labels: documentation

#41 Refactor/change colors
  lib/src/core/ui/design_system/colors/monochromatic_colors.dart
  lib/src/core/ui/design_system/colors/primary_colors.dart
  lib/src/core/ui/design_system/widgets/buttons/solid_button.dart
  lib/src/core/ui/widgets/cards/person_information_card.dart
  lib/src/core/ui/widgets/cards/progress_card.dart
  lib/src/modules/activities/ui/widgets/activity_progress_card_widget.dart
  lib/src/modules/activities/ui/widgets/teacher_information_card_widget.dart
  lib/src/modules/calendar/ui/pages/calendar_page.dart
  lib/src/modules/notifications/ui/widgets/notification_card.dart
  lib/src/modules/onboarding/ui/widgets/onboarding_bottom_sheet.dart
Labels: refactor

#49 Test/notifications
  lib/src/core/exceptions/exceptions.dart
  lib/src/core/exceptions/generic_exception.dart
  lib/src/core/exceptions/invalid_credentials_exception.dart
  lib/src/core/exceptions/invalid_type_exception.dart
  lib/src/core/exceptions/not_found_exception.dart
  lib/src/core/exceptions/unauthorized_exception.dart
  lib/src/core/exceptions/unknow_exception.dart
  lib/src/core/services/local_storage/data/services/local_storage_shared_preferences_service_impl.dart
  lib/src/modules/authentication/data/services/auth_mock_service_impl.dart
  lib/src/modules/authentication/ui/store/login_store.dart
  lib/src/modules/notifications/data/services/notification_local_service_impl.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generated_mocks.dart
  test/mocks/generated_mocks.mocks.dart
  test/mocks/notification_entity_mock.dart
  test/src/core/services/local_storage/data/services/local_storage_shared_preferences_service_impl_test.dart
  test/src/modules/notifications/data/services/notification_local_service_impl_test.dart
  test/src/modules/notifications/domain/enums/notification_link_type_enum_test.dart
  test/src/modules/notifications/domain/enums/notification_status_enum_test.dart
Labels: enhancement

#50 fix: change logout button position on profile page
  lib/src/modules/profile/ui/pages/profile_page.dart
Labels: refactor

#52 feat: add flutter ci with tests and analyze
  .github/workflows/ci.yml
Labels: feature

#54 refactor: remove pull request on CI
  .github/workflows/ci.yml
Labels: refactor

#58 Added new unit tests and implemented new tests in existing ones for code coverage
  lib/src/core/constants/local_storage_key.dart
  lib/src/core/exceptions/generic_exception.dart
  lib/src/modules/authentication/domain/dtos/login_with_student_registration_dto.dart
  lib/src/modules/authentication/domain/entities/user_entity.dart
  lib/src/modules/campaigns/ui/parameters/campaign_page_parameter.dart
  test/src/core/extensions/string_extension_test.dart
  test/src/core/utils/nullable_value_test.dart
  test/src/modules/authentication/domain/entities/user_entity_test.dart
  test/src/modules/notifications/data/services/notification_local_service_impl_test.dart
Labels: feature
